name: "Run Renovate"

on:
  # Once a month, on the 1st at 00:00 UTC
  schedule:
    - cron: "0 0 1 * *"
  # Optionally, trigger manually...
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Validate Renovate JSON
        run: jq type renovate.json

      - uses: actions/create-github-app-token@v1.11.1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Renovate Bot GitHub Action
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          # Onboarding not needed for self hosted
          RENOVATE_ONBOARDING: "false"
          # Username for GitHub authentication (should match GitHub App name + [bot])
          RENOVATE_USERNAME: "hobbyfarm-renovate[bot]"
          # Git commit author used, must match GitHub App
          RENOVATE_GIT_AUTHOR: "hobbyfarm-renovate <123456789+hobbyfarm-renovate[bot]@users.noreply.github.com>"
          # Use GitHub API to create commits (this allows for signed commits from GitHub App)
          RENOVATE_PLATFORM_COMMIT: "true"
        uses: renovatebot/github-action@v36.0.0
        with:
          configurationFile: 'renovate.json'
          token: ${{ steps.app-token.outputs.token }}
          useSlim: true
